<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../UPA.Core/UPA.Core.csproj" />
    <ProjectReference Include="../UPA.ProjectModel/UPA.ProjectModel.csproj" />
  </ItemGroup>
</Project>
