<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\UPA.Pipeline\UPA.Pipeline.csproj" />
    <ProjectReference Include="..\..\src\UPA.MVP3.TrustEmission\UPA.MVP3.TrustEmission.csproj" />
    <ProjectReference Include="..\..\src\UPA.Core\UPA.Core.csproj" />
    <ProjectReference Include="..\..\src\UPA.ProjectModel\UPA.ProjectModel.csproj" />
    <ProjectReference Include="..\..\..\..\UPA-MVP2\artifacts\v20.0-final\src\UPA.VerificationTrustAnchor\UPA.VerificationTrustAnchor.csproj" />
    <ProjectReference Include="..\..\src\UPA.Analysis\UPA.Analysis.csproj" />
  </ItemGroup>

</Project>
