<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../UnityPackage/UPA.UnityExecutor/Editor/UPAUnityCommandParser.cs" Link="UnityCommandParser.cs" />
    <ProjectReference Include="../UPA.ProjectModel/UPA.ProjectModel.csproj" />
    <ProjectReference Include="../UPA.Health/UPA.Health.csproj" />
  </ItemGroup>
</Project>
